# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# C:\b\abs_a9fyfijr7c\clone\recipe, last modified Thu Jun 12 16:23:17 2025
# ------------------------------------------------

package:
  name: notebook
  version: 7.3.2
source:
  url: https://pypi.io/packages/source/n/notebook/notebook-7.3.2.tar.gz
  sha256: 705e83a1785f45b383bf3ee13cb76680b92d24f56fb0c7d2136fe1d850cd3ca8
build:
  number: '1'
  entry_points:
    - jupyter-notebook = notebook.app:main
  no_link:
    - Menu/notebook_menu.json
  string: py313haa95532_1
requirements:
  host:
    - anyio 4.7.0 py313haa95532_0
    - argon2-cffi 21.3.0 pyhd3eb1b0_0
    - argon2-cffi-bindings 21.2.0 py313h827c3e9_1
    - asttokens 3.0.0 py313haa95532_0
    - async-lru 2.0.4 py313haa95532_0
    - attrs 24.3.0 py313haa95532_0
    - babel 2.16.0 py313haa95532_0
    - beautifulsoup4 4.12.3 py313haa95532_0
    - bleach 6.2.0 py313haa95532_0
    - brotli-python 1.0.9 py313h5da7b33_9
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.2.25 haa95532_0
    - certifi 2025.4.26 py313haa95532_0
    - cffi 1.17.1 py313h827c3e9_1
    - charset-normalizer 3.3.2 pyhd3eb1b0_0
    - colorama 0.4.6 py313haa95532_0
    - comm 0.2.1 py313haa95532_0
    - debugpy 1.8.11 py313h5da7b33_0
    - decorator 5.1.1 pyhd3eb1b0_0
    - defusedxml 0.7.1 pyhd3eb1b0_0
    - executing 0.8.3 pyhd3eb1b0_0
    - expat 2.7.1 h8ddb27b_0
    - h11 0.16.0 py313haa95532_0
    - hatch-jupyter-builder 0.9.1 py313haa95532_0
    - hatchling 1.27.0 py313haa95532_0
    - httpcore 1.0.9 py313haa95532_0
    - httpx 0.28.1 py313haa95532_0
    - idna 3.7 py313haa95532_0
    - ipykernel 6.29.5 py313haa95532_1
    - ipython 9.1.0 py313haa95532_0
    - ipython_pygments_lexers 1.1.1 py313haa95532_0
    - jedi 0.19.2 py313haa95532_0
    - jinja2 3.1.6 py313haa95532_0
    - json5 0.9.25 py313haa95532_0
    - jsonschema 4.23.0 py313haa95532_0
    - jsonschema-specifications 2023.7.1 py313haa95532_0
    - jupyter-lsp 2.2.5 py313haa95532_0
    - jupyter_client 8.6.3 py313haa95532_0
    - jupyter_core 5.7.2 py313haa95532_0
    - jupyter_events 0.12.0 py313haa95532_0
    - jupyter_server 2.15.0 py313haa95532_0
    - jupyter_server_terminals 0.5.3 py313haa95532_0
    - jupyterlab 4.3.4 py313haa95532_0
    - jupyterlab_pygments 0.3.0 py313haa95532_0
    - jupyterlab_server 2.27.3 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libsodium 1.0.18 h62dcd97_0
    - markupsafe 3.0.2 py313h827c3e9_0
    - matplotlib-inline 0.1.6 py313haa95532_0
    - mistune 3.1.2 py313haa95532_0
    - nbclient 0.10.2 py313haa95532_0
    - nbconvert-core 7.16.6 py313haa95532_0
    - nbformat 5.10.4 py313haa95532_0
    - nest-asyncio 1.6.0 py313haa95532_0
    - notebook-shim 0.2.4 py313haa95532_0
    - openssl 3.0.16 h3f729d1_0
    - overrides 7.4.0 py313haa95532_0
    - packaging 24.2 py313haa95532_0
    - pandocfilters 1.5.0 pyhd3eb1b0_0
    - parso 0.8.4 py313haa95532_0
    - pathspec 0.10.3 py313haa95532_0
    - pip 25.1 pyhc872135_2
    - platformdirs 4.3.7 py313haa95532_0
    - pluggy 1.5.0 py313haa95532_0
    - prometheus_client 0.21.1 py313haa95532_0
    - prompt-toolkit 3.0.43 py313haa95532_0
    - prompt_toolkit 3.0.43 hd3eb1b0_0
    - psutil 5.9.0 py313h827c3e9_1
    - pure_eval 0.2.2 pyhd3eb1b0_0
    - pycparser 2.21 pyhd3eb1b0_0
    - pygments 2.19.1 py313haa95532_0
    - pysocks 1.7.1 py313haa95532_0
    - python 3.13.4 h286a616_100_cp313
    - python-dateutil 2.9.0post0 py313haa95532_2
    - python-fastjsonschema 2.20.0 py313haa95532_0
    - python-json-logger 3.2.1 py313haa95532_0
    - python_abi 3.13 0_cp313
    - pywin32 308 py313h5da7b33_0
    - pywinpty 2.0.15 py313h72d21ff_0
    - pyyaml 6.0.2 py313h827c3e9_0
    - pyzmq 26.2.0 py313h5da7b33_0
    - referencing 0.30.2 py313haa95532_0
    - requests 2.32.3 py313haa95532_1
    - rfc3339-validator 0.1.4 py313haa95532_0
    - rfc3986-validator 0.1.1 py313haa95532_0
    - rpds-py 0.22.3 py313h636fa0f_0
    - send2trash 1.8.2 py313haa95532_1
    - setuptools 78.1.1 py313haa95532_0
    - six 1.17.0 py313haa95532_0
    - sniffio 1.3.0 py313haa95532_0
    - soupsieve 2.5 py313haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - stack_data 0.2.0 pyhd3eb1b0_0
    - terminado 0.17.1 py313haa95532_0
    - tinycss2 1.4.0 py313haa95532_0
    - tk 8.6.14 h5e9d12e_1
    - tornado 6.5.1 py313h827c3e9_0
    - traitlets 5.14.3 py313haa95532_0
    - trove-classifiers 2024.10.14 py313haa95532_0
    - typing-extensions 4.12.2 py313haa95532_0
    - typing_extensions 4.12.2 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - urllib3 2.3.0 py313haa95532_0
    - vc 14.42 haa95532_5
    - vs2015_runtime 14.42.34433 hbfb602d_5
    - wcwidth 0.2.5 pyhd3eb1b0_0
    - webencodings 0.5.1 py313haa95532_2
    - websocket-client 1.8.0 py313haa95532_0
    - wheel 0.45.1 py313haa95532_0
    - win_inet_pton 1.1.0 py313haa95532_0
    - winpty 0.4.3 4
    - xz 5.6.4 h4754444_1
    - yaml 0.2.5 he774522_0
    - zeromq 4.3.5 hd77b12b_0
    - zlib 1.2.13 h8cc25b3_1
  run:
    - jupyter_server >=2.4.0,<3
    - jupyterlab >=4.3.4,<4.4
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2,<0.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - tornado >=6.2.0
test:
  imports:
    - notebook
  requires:
    - pip
    - ripgrep
  commands:
    - pip check
    - jupyter notebook -h
    - jupyter-notebook -h
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - type labextensions | rg "@jupyter-notebook/lab-extension.*ok"
app:
  entry: jupyter-notebook
  icon: jupyter.png
  summary: Jupyter Notebook
  type: web
  cli_opts:
    - name: port
      args: --port %s
      default: '8080'
      summary: Server port ...
about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - notebook/labextension/static/third-party-licenses.json
    - notebook/static/third-party-licenses.json
  summary: A web-based notebook environment for interactive computing
  description: 'The Jupyter notebook is a web-based notebook environment for interactive
    computing.

    '
  dev_url: https://github.com/jupyter/notebook
  doc_url: https://jupyter-notebook.readthedocs.io
extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
    - gnestor
    - jakirkham
    - lresende
    - minrk
    - pelson
    - takluyver
  final: true
  copy_test_source_files: true
  sha: 2619e6d070f40fcb229883642fbd6d8c117b51be
  remote_url: git@github.com:AnacondaRecipes/notebook-feedstock.git
  flow_run_id: a9c1abfb-c9c3-4196-83a8-d8af6ec77d8e
