# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# C:\b\abs_9ctyfgpncn\clone\recipe, last modified Tue Mar 11 16:43:12 2025
# ------------------------------------------------

package:
  name: notebook-shim
  version: 0.2.4
source:
  sha256: b4b2cfa1b65d98307ca24361f5b30fe785b53c3fd07b7a47e89acb5e6ac638cb
  url: https://pypi.io/packages/source/n/notebook-shim/notebook_shim-0.2.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_9ctyfgpncn\\croot\\notebook-shim_1741707829491\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -v
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.2.25 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - hatchling 1.27.0 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - openssl 3.0.16 h3f729d1_0
    - packaging 24.2 py313haa95532_0
    - pathspec 0.10.3 py313haa95532_0
    - pip 25.0 py313haa95532_0
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.2 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - setuptools 75.8.0 py313haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - trove-classifiers 2024.10.14 py313haa95532_0
    - tzdata 2025a h04d1e81_0
    - vc 14.42 haa95532_4
    - vs2015_runtime 14.42.34433 he0abc0d_4
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - jupyter_server >=1.8,<3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - notebook_shim
  requires:
    - pip
about:
  description: 'This project provides a way for JupyterLab and other frontends to
    switch to Jupyter Server for their Python Web application backend.

    '
  dev_url: https://github.com/jupyter/notebook_shim
  doc_url: https://github.com/jupyter/notebook_shim/blob/main/README.md
  home: https://github.com/jupyter/notebook_shim
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A shim layer for notebook traits and config
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9cdda948-d463-404f-8cd2-cb1b97106592
  recipe-maintainers:
    - Zsailer
    - bollwyvl
    - jtpio
  remote_url: git@github.com:AnacondaRecipes/notebook-shim-feedstock.git
  sha: 7694986b8b26cb5905c3c1de875f2caa3ef64d29
